- .github/linters/.markdown-link.yml
- .github/linters/.markdown-lint.yml
- Cargo.toml
- README.md
- RELEASES.md
- examples/clash_handling.rs
- src/action_state.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/input_mocking.rs
- src/lib.rs
- src/systems.rs
- src/user_input.rs
- tests/clashes.rs
- tests/integration.rs
Fixes #23.
In many applications, overlapping inputs are special cased, to avoid surprising results, especially with modifier keys.
If `Ctrl + V` and `Ctrl + Shift + V` only pastes without formatting, rather than doing that *and* pasting normally.
Two inputs are said to clash if one is a strict subset of the other.
Allow users to configure their input maps to decide how they want to handle clashing inputs.
```rust
pub enum ClashStrategy {
/// All matching inputs will always be pressed
PressAll,
/// Only press the action that corresponds to the longest chord
PrioritizeLongest,
/// If the [`UserInput`] contains a modifier key (defined at the input map level), press that action over any unmodified action.
///
/// If more than one matching action uses a modifier, break ties based on number of …
```
> Input clash handling

- src/buttonlike_user_input.rs
- src/clashing_inputs.rs
- src/input_map.rs
In this PR I replaced all size-related functions to operate with usize instead of u8 since the conversion happens anyway under the hood.
> Use usize for contianer sizes

- Cargo.toml
To run examples there should be more dependencies. Otherwise you will get crash on startup.
> Fix missing dependencies

- RELEASES.md
- src/buttonlike_user_input.rs
- src/clashing_inputs.rs
- src/display_impl.rs
- src/input_map.rs
- src/input_mocking.rs
In this PR I make `InputMap` API more map-like. Also now it panics when something is going wrong instead of silently fails.
Should I replace `get` to return an iterator instead of `PetitiSet` directly?
> Simplify InputMap

- RELEASES.md
- src/input_map.rs
Works exactly as `PetitSet::remove`, but for specified `action`.
> Add InputMap::remove

- src/action_state.rs
Before this change, `.insert(...)` on `ActionState::button_states` would duplicate items. Changed those lines to direct assignments so duplication doesn't occur.
> Changed `ActionState.button_states` inserts into direct assignments

- src/input_map.rs
Otherwise users won't be able to deserialize empty mappings.
> Enable default for serde

- src/input_map.rs
In previous PR I added a method to iterate over inputs. But I realized that such iteration should be with action like in normal map.
So I renamed the submitted `iter()` method into `iter_inputs()` and added `iter()` that iterates over actions with inputs.
I also have to delete `IntoIter` currently because we can't use opaque type in traits without nightly compiler.
If you know how to implement it properly - I would appreciate your advice. But for now I removed it.
> Iterate over actions with mapping by default

- Cargo.toml
- examples/binding_menu.rs
I added additional helper `iter_with_actions` and an example of binding menu. Suggestions are welcome :)
Backported from [my game](https://github.com/gardum-game/gardum) (currently at prototype stage).
This PR requires #96.
**Screenshots:**
> Binding menu example

- README.md
- RELEASES.md
- examples/arpg_indirection.rs
- examples/minimal.rs
- examples/press_duration.rs
- src/action_state.rs
- src/buttonlike.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/lib.rs
- src/plugin.rs
- src/systems.rs
- Reasoning about and writing code for `VirtualButtonState` was a disaster, due to all of the extra information stored in it
- The default value for `VirtualButtonState` was "just released", and we could not change this due to the intertwining of button state and timing information.
- APIs to access timing information were not discoverable or ergonomic.
- refactor `VirtualButtonState` into `ActionData`, which stores reasons pressed, timing and a simple `ButtonState` enum
- change the default value to "released", rather than "just released"
- expose convenient APIs to access timing information directly on `ActionState`
- give users the ability to directly control `ActionData` for when they want to do unusual things like "skip directly to pressed"
> Refactor VirtualButtonState

- RELEASES.md
- src/input_mocking.rs
- src/user_input.rs
Being able to release specific inputs is very useful for more robust tests.
> Provide functionality to release inputs during mocking

- RELEASES.md
- src/action_state.rs
- src/buttonlike.rs
- src/lib.rs
- src/plugin.rs
- src/systems.rs
- tests/integration.rs
1. Allows users to freeze (and unfreeze) entire action states, causing them to ignore any attempts to press or release their actions. 
2. Provides a fix to the underlying issue in #86.
3. We can reuse this functionality in combination with `release_all` to replace #106 with a more elegant and flexible API.
> Add ActionState::freeze

- src/action_state.rs
Branch configuration was misconfigured, and so tests were not required to pass.
Fixed now!
> Fix dev-branch

- RELEASES.md
- src/action_state.rs
- src/lib.rs
- src/plugin.rs
- src/systems.rs
- tests/integration.rs
`ActionState::freeze` was introduced to consume actions. But it turns out not very ergonomic. Also `freeze` requires to spawn an entity or init the resource should which is not always the case. In this iteration I used run criteria to make the code nicer.
Also I extended `disable_input` test to check if global and entity input both released on disable.
> Replace freeze API with improved DisableInput resource

- RELEASES.md
- examples/consuming_actions.rs
- src/action_state.rs
*Finally* fixes the problem outlined in #108. See the attached example for a nice demonstration of how this works and why it's useful.
Full credit to @shatur for the final idea on the mechanism.
> Add ActionState::consume

- README.md
heya! I was using leafwing today and got a warning when I copy/pasted the name from the readme instructions because the crate name uses dashes and not underscores.
Not sure if you want it to show underscores intentionally but figured I'd PR a change anyway.
thanks for the crate, it's very useful!
> update crate name in README

- Cargo.toml
This way you can run the examples with gamepad support. It was kind of confusing to me as somebody trying to run the examples that none of the gamepad inputs were working.
A lot of people probably wouldn't know to do this themselves.
> Add Bevy Gilrs to Dev Dependency Features

- README.md
- RELEASES.md
- examples/arpg_indirection.rs
- examples/binding_menu.rs
- examples/clash_handling.rs
- examples/consuming_actions.rs
- examples/minimal.rs
- examples/multiplayer.rs
- examples/press_duration.rs
- examples/send_actions_over_network.rs
- examples/single_player.rs
- examples/ui_driven_actions.rs
- src/action_state.rs
- src/clashing_inputs.rs
- src/input_map.rs
- tests/clashes.rs
- tests/integration.rs
User feedback has been unanimous: this direction makes more sense!
Sorry about the tedious migration work, but better now than later 😅 Just chase the compiler errors!
> Reverse order of `InputMap` from `(action, input)` to `(input, action)`

- README.md
- RELEASES.md
- examples/analog_stick.rs
- examples/axis_inputs.rs
- examples/binding_menu.rs
- examples/virtual_dpad.rs
- src/action_state.rs
- src/axislike.rs
- src/clashing_inputs.rs
- src/display_impl.rs
- src/input_map.rs
- src/input_mocking.rs
- src/lib.rs
- src/systems.rs
- src/user_input.rs
This should be functionally ready, but I haven't necessarily done my due diligence with the doc strings or self-review yet. I also need to add a new example demonstrating the use of the controller axes. I'll get to that tomorrow probably.
The PR ended up somewhat large, but the changes are pretty straight-forward.
- Now every event kind has a "value". This will be between -1.0 and 1.0.
- If you wanted to implement simple character bindings with an analog stick you could do this:
```rust
let input_map = InputMap::<PlayerAction>::new(vec![
(
PlayerAction::Right,
GamepadAxisThreshold {
axis: GamepadAxisType::LeftStickX,
comparison: GamepadAxisComparison::Greater,
threshold: 0.1,
},
),
(
PlayerAction::Left,
GamepadAxisThreshold {
axis: GamepadAxisType::LeftStickX,
comparison: …
```
> Add Support For Gamepad Axes

- Cargo.toml
- RELEASES.md
- macros/Cargo.toml
This reverts commit ba4e704dac4cdde79f4c270a73e0f1282b764dc2, PR #161.
Fixes #160. The approach there worked, but since we can't rename crates we must do this instead.
> Fix conflict between macro crate name and version

- examples/axis_inputs.rs
- src/action_state.rs
- src/axislike.rs
- src/clashing_inputs.rs
- src/display_impl.rs
- src/lib.rs
- src/user_input.rs
Fixes #159.
I've left these relatively minimal to start; the explicit construction isn't too bad.
I did a bit of shuffling; the user input file was too large and these made sense in `axislike.rs`.
I don't love that users can construct / mutate these types into weird or bad states still. I think that's best left for another PR though, it's not trivial. See #166.
> Add builder methods for new axislike input types

- RELEASES.md
- src/action_state.rs
- src/input_map.rs
- tests/integration.rs
This was originally intended to be used as part of #151, but turned out not to be needed.
While technically useful for users, it involved significant complexity and computational overhead.
> Remove ActionState::reasons_pressed API

- src/action_state.rs
- src/axislike.rs
- src/input_mocking.rs
- src/user_input.rs
Resolves a FIXME from #151 by @zicklag.
Not *thrilled* with the fact that this is only used for input mocking, but updating the `SingleGamepadAxis` / `DualGamepadAxis` field dynamically is contrary to the general data flow of the library.
Storing the target value in the `UserInput` struct also allows us to avoid polluting the input mocking API for the very rare case.
> Set axis values when mocking user input

- Cargo.toml
- examples/axis_inputs.rs
- examples/binding_menu.rs
- src/action_state.rs
- src/axislike.rs
- src/input_map.rs
- src/input_streams.rs
This makes sure that SingleAxis inputs will report a value of 0.0 if the
axis value is not withing the triggering zone. This makes it possible to
create a virtual gamepad made up of multiple single-axis inputs on the
same stick.
I ran into a scenario where in my game input mapping screen I want to map inputs to player actions such as move up, move down, etc., in a table like most game input screens are laid out. This scenario meant that it's easier to structure the input binding as a virtual DPad, even when the player is inputting analog stick directions, and they could technically put in different axes for different directions.
This commit makes the Virtual DPad output a proper axis pair data even when it contains single axis inputs for some or all of the directions. Before this commit …
> Support Single Axis Inputs in Virtual DPads

- Cargo.toml
- examples/arpg_indirection.rs
- examples/consuming_actions.rs
- examples/send_actions_over_network.rs
- examples/ui_driven_actions.rs
- src/action_state.rs
- src/axislike.rs
- src/buttonlike.rs
- src/clashing_inputs.rs
- src/errors.rs
- src/input_map.rs
- src/input_mocking.rs
- src/input_streams.rs
- src/lib.rs
- src/orientation.rs
- src/plugin.rs
- src/systems.rs
- src/user_input.rs
- tests/clashes.rs
- tests/integration.rs
- tests/mouse_wheel.rs
This is a) much cleaner and easier to maintain b) makes it easier for others to patch this crate to a specific version and c) slightly more robust to bevy shuffling code around.
> Depend on Bevy directly

- src/input_mocking.rs
I tried to compile without default features and it failed because of a missing feature check. This fixes it.
> Fix Compile Without UI Feature

- src/clashing_inputs.rs
Every action clash currently prints a message. This seems unintended.
> Don't print a message for every clash

- src/axislike.rs
It was incorrectly using the y-axis from the left stick.
> Make `DualAxis::right_stick()` use the correct y-axis

- RELEASES.md
- src/plugin.rs
I added the following as was suggested in #227:
- Make `_phantom` field public and rename into `phantom`.
- Add `ToggleActions::new`.
- Add `ToggleActions::ENABLED` and `ToggleActions::DISABLED`. Do we really need them? :thinking:
> Improve ToggleActions

- src/action_state.rs
Manipulating `ActionData` works well if you want to use one of the methods like `press`, `release`, etc. But it's a bit more challenging if you a) want to do something outside the limited setters and b) don't want to get into the specifics of how `ActionData` should be set up.
This lets me do the following:
```
let mut direction = Vec2::ZERO;
if actions.pressed(Action::Forward) {
direction.x += 1.;
}
if actions.pressed(Action::Backward) {
direction.x -= 1.;
}
if actions.pressed(Action::Left) {
direction.y += 1.;
}
if actions.pressed(Action::Right) {
direction.y -= 1.;
}
let mut data = navigation.action_data_mut(NavigationAction::Move);
if direction.length() != 0. {
navigation.press(NavigationAction::Move);
data.axis_pair = Some(direction.into());
} else { …
```
> Add `ActionState::action_data_mut` for retrieving mutable state for an action

- RELEASES.md
- src/action_state.rs
- src/input_map.rs
Clippy now emits warnings when you derive `PartialEq`, but not `Eq` when it is possible.
In the `cargo run -p ci` script, those warnings become errors.
This PR fixes these warnings and must be merged before #234 and #235.
> Fix clippy warnings to also derive `Eq`

- tools/ci/src/main.rs
Closes #199.
This expands the CI script to also run `cargo check` with no features and default features to catch potential errors with the feature configuration.
> Run `cargo check` with no features and default features in CI

- Cargo.toml
- RELEASES.md
- src/action_state.rs
- src/input_map.rs
- src/input_streams.rs
The gamepad axis type wasn't making sure the returned value was within the range of the axis thresholds.
> Make Sure Gampad Axis Value Is Within Deadzone

- tools/ci/src/main.rs
Closes #201.
Note that this doesn't _run_ the examples, but I think running clippy on them gives the best ROI.
Actually running may have several disadvantages:
- It's hard to set up, you'd probably need to get a list of all examples somehow.
- It could reduce CI times substantially, depending on the timeout.
- It is flaky, sometimes it might catch an error and sometimes not.
Also note that this way of setting up CI has the disadvantage that it's not run in parallel.
This might not scale well, especially with the examples now.
> Run clippy on examples in CI

- RELEASES.md
- src/plugin.rs
- src/systems.rs
- tests/integration.rs
Fixes #244
Adds a system that runs on PostUpdate that will release all inputs on an ActionState if a corresponding InputMap was removed.
Uses removal detection as described in https://bevy-cheatbook.github.io/programming/removal-detection.html
> Release inputs when InputMap is removed

- RELEASES.md
- src/action_state.rs
- src/cooldown.rs
- src/lib.rs
- src/user_input.rs
> - You can now store `Cooldown`s in the `ActionState` on a per-action basis.
>   - Set cooldowns for actions using `ActionState::set_cooldown(action, cooldown)`.
>   - Use `ActionState::ready` with `ActionState::trigger_cooldown` as part of your action loop!
>   - Cooldowns are automatically elapsed whenever `ActionState::tick` is called (this will happen automatically if you add the plugin).
Co-authored with @bzm3r!
> Store per-action cooldowns

- RELEASES.md
- src/display_impl.rs
- src/input_map.rs
- src/input_streams.rs
- src/lib.rs
- src/user_input.rs
---
name: Pull request
about: Fix a bug, add a feature, improve some docs
title: ''
labels: "S: needs-triage"
assignees: ''
---
Specifying chords that involved modifier keys was tedious and error-prone, as keycodes are specific to either the left or right variant.
Fixes #211.
Added the `Modifier` enum, which can be stored in an `InputKind` and maps to both the left and right variants of each modifier.
Several related helper methods have also been added.
> Add direct support for modifier keys

- Cargo.toml
- RELEASES.md
- src/input_map.rs
Attemp to add custom serde implementation for `InputMap`
```Rust
InputMap(
map: {
Run:  [Single(Keyboard(LShift)),Single(Keyboard(RShift))],
Jump: [Single(Keyboard(Space))],
Hide: [Chord([Some(Keyboard(R)),Some(Keyboard(E)),None,None,None,None,None,None])]
}
)
```
To achieve this format, I added four new traits::
- `impl<A: Actionlike> FromIterator<(A, UserInput)> for InputMap<A>`
- `impl<A: Actionlike> From<HashMap<A, Vec<UserInput>>> for InputMap<A>`
- `impl<A> Serialize for InputMap<A> where A: Actionlike + Serialize + Eq + Hash + Ord`
- `Eq + Hash` since I'm using map to serialize inputs
- `Ord` is for `BTreeMap` so all actions will always serialize in the same order (I mainly need this to test serialization)
- `impl<'de, A> Deserialize<'de> for InputMap<A> where A: Actionlike + …
> Custom serde implementation for `InputMap`

- src/axislike.rs
This adds `VirtualAxis::ad` and `VirtualAxis::wd`; the latter uses the traditional Bevy axis direction (Y up).
> Add VirtualAxis method analogous to VirtualDPad::wasd()

- RELEASES.md
- src/input_streams.rs
- src/plugin.rs
- src/systems.rs
Unfortunately, we can't clear events and inputs - it "breaks" other plugins, such as egui because it relies on these bevy resources.
For example, without this PR after clicking on a widget egui returns `false` from `wants_pointer_input` which results in clicks through widgets.
> Fix egui feature

- src/systems.rs
`wants_pointer_input` sometimes returns `false` after clicking or holding a button over a widget, so `is_pointer_over_area` is also needed. A follow up for #289.
> Fix clicking through egui widgets

- src/systems.rs
This function is never used and should have been removed in #289.
> Remove unused consume_input_events_when_egui_wants_focus

- Cargo.toml
- RELEASES.md
- src/input_map.rs
- Bring changes from #282 into main
- Add `TypeUuid` for `InputMap` to be able use it as asset without wrapper
> Custom serde implementation and `TypeUuid` for `InputMap`

- RELEASES.md
- src/action_state.rs
- src/axislike.rs
- src/buttonlike.rs
- src/plugin.rs
Makes it possible to inspect:
And also necessary for `ActionState` to be rolled back by bevy_ggrs.
> Derive `Reflect` for `ActionState`

- Cargo.toml
- RELEASES.md
- src/lib.rs
- src/press_scheduler.rs
- src/systems.rs
- tests/integration.rs
Introduce an easy way to trigger action presses from within the update loop (e.g. a UI implemented with egui)
Implement the optional PressScheduler helper which lets users easily schedule presses that are realized on the next frame
I added some preliminary documentation, but I'm sure it could be improved.
> Implement PressScheduler

- RELEASES.md
- macros/src/actionlike.rs
- src/action_state.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/lib.rs
- src/press_scheduler.rs
This will allow more advanced and dynamic `Actionlike` impls to exist.
> Convert the N_VARIANTS constant to a function

- RELEASES.md
- src/action_state.rs
Some state transitions (E.g. pause/unpause, menu transitions) need to nuke action states from orbit. It isn't enough to release them since, say, `just_pressed` might trigger if a UI and game action share a binding with a game action. Currently I manually consume actions if a binding to start/exit a menu conflicts with a game action, but this assumes a specific binding and doesn't allow for flexibility.
While disabling actions is also possible, it requires disabling/enabling multiple mappings at multiple transition points. I found it much easier to reason about clearing all action state on game pause/start/resume than ensuring that multiple UI menus manually disable and re-enable multiple action mappings.
`ActionState::consume_all()` can be run at state transitions where action state …
> Add `ActionState::consume_all()` to consume all actions.

- .github/workflows/ci.yml
- Use the [Leafwing-Studios/cargo-cache](https://github.com/Leafwing-Studios/cargo-cache) action to fix CI caching issues
- Also build and test on Mac OS, in preparation for the platform specific code introduced in #312.
In the future, we should think about splitting up the CI action as it does a lot and is not parallelized.
We also probably need a WASM check for the WASM specific scan codes.
> Use cargo-cache for CI caching, build for Mac OS

- src/input_map.rs
This has no functional change, but just switches the names of the destructured tuple values so that when the are passed to `insert` that they match function signature.
> Switch destructured tuple names to match insert signature

- RELEASES.md
- examples/mouse_position.rs
- examples/ui_driven_actions.rs
- src/action_state.rs
- src/orientation.rs
- src/systems.rs
- tests/integration.rs
Problem
A lot of games require mouse position as an input in some way. However, in games with multiple windows or screens, this is not a straight forward input to get, and how to transform from screen space to world space, or if you need to at all, is a bit dependent on the use case, so it's hard to have a one size fits all axis type.
Solution
This crates great design makes it relatively easy to drive a mouse position action from an ActionStateDriver, it just needs a quick example to get the ball rolling for how you can add the capability to your own game, which this PR adds.
This PR also makes a small change to ActionStateDriver to let it drive multiple entities instead of just one. I think this will be a big win long term for games that will need mouse data, or other driven action data, …
> Mouse position

- RELEASES.md
- src/axislike.rs
- src/input_streams.rs
- tests/gamepad_axis.rs
- tests/mouse_motion.rs
- tests/mouse_wheel.rs
Fixes #247.
Adds `inverted`, `inverted_x`, and `inverted_y` builder-style functions for `SingleAxis`, `DualAxis`, and `VirtualDPad`, where appropriate. The `SingleAxis` implementation uses an `inverted` field, the `DualAxis` implementation just inverts its internal axes, and the `VirtualDPad` implementation swaps the relevant inputs.
Current tests pass, but I haven't written any yet to test inversion.
> Add Inversion to SingleAxis, DualAxis, and VirtualDPad

- examples/mouse_position.rs
Small but critical fix to one of the examples.
Fixes: #367
> examples: Move update_cursor_state_from_window to Update

- RELEASES.md
- src/axislike.rs
- src/input_map.rs
- src/input_streams.rs
- src/lib.rs
- src/user_input.rs
- tests/gamepad_axis.rs
- tests/mouse_motion.rs
- tests/mouse_wheel.rs
Currently, the only type of deadzone for a `DualAxis` is a cross shape. This shape is preferred for some instances, like in Rocket League, as the cross-shape deadzone makes directional flipping easier. However, there are instances where a circular or rectangular deadzone is preferred, like a twin-stick shooter.
Adds `DeadzoneShape` to `DualAxis`, which allows the user to choose between a circle, rectangle, and a cross for the deadzone shape.
From manual tests, the shapes appear to be correct and all work. This pr also passed `cargo test`.
1. Is `extract_dual_axis_data()` the correct method to test the different shapes?
2. Adding `include_deadzone: bool` to `input_value()` feels a little gross, but I didn't find a better way to get the input_value of a `SingleAxis` without it running its …
> Deadzone shapes

- src/axislike.rs
There might be some confusion as to what range values should be used with `DeadZoneShape`. This added doc explains that the values should be in the range `0..=1.0`.
> Update deadzone docs

- RELEASES.md
- src/input_streams.rs
> Fix `InputMap` not receiving inputs from all gamepads

- README.md
Since this repository no longer does all the development on a dev branch the instructions in the readme noting this are no longer accurate.
Therefore this PR removes this note, and since this was the only instruction outside of the "Getting started", I've removed the "Instructions" header and upgraded the "Getting started" header.
> Remove note about the dev branch in the readme

- src/clashing_inputs.rs
- src/input_map.rs
- src/input_streams.rs
- src/plugin.rs
- src/systems.rs
Fix doc error due to `redundant explicit link target` that was introduced in Rust 1.73
> Fix `redundant explicit link target` docs error

- Cargo.toml
- RELEASES.md
- src/systems.rs
Adds the `block_ui_interactions` feature, which allows users to optionally disable #355. 
I chose to place the feature in the default feature to keep the current behavior. As for the feature itself, I chose not to turn on `ui` or `bevy_ui`. This makes users explicitly state that `ui` is on, and they want to block ui interaction as well. That does mean that turning on `block_ui_interactions` will do nothing, as it relies on `ui`.
> Add `block_ui_interactions` feature

- src/axislike.rs
- tests/gamepad_axis.rs
Having the boundary of the `DeadZoneShape` mean that it is outside is in line with #395. This also means that any `DeadZoneShape` that has a volume of 0 will let all input values be read.
> Change deadzone to have boundary mean outside shape

- RELEASES.md
- src/axislike.rs
Adds a simple helper for two keys making up an axis beyond the `ad`, `ws` etc. provided. Usage is just:
```rs
input_map.insert(VirtualAxis::from_keys(KeyCode::F, KeyCode::R), Movement::Vertical);
```
Also migrated `ad`, `ws` etc. to use the new helper.
> Add `VirtualAxis::from_keys` Helper

- Cargo.toml
- RELEASES.md
- src/plugin.rs
- src/systems.rs
I tested `minimal.rs` using the egui feature just to make sure nothing broke, and it works.
> Add back `bevy_egui` to LWIM 0.11

- RELEASES.md
- src/plugin.rs
When multiple `ToggleActions` exist, setting even one to disabled will release all input from other actions. Here is an example that fails on current main, but works with this pr:
```rust
fn main() {
App::new()
.add_plugins(DefaultPlugins)
.add_plugins(InputManagerPlugin::<Action>::default())
.add_plugins(InputManagerPlugin::<Action2>::default())
.insert_resource(ToggleActions::<Action>::ENABLED)
.insert_resource(ToggleActions::<Action2>::DISABLED)
.add_systems(Startup, spawn_player)
.add_systems(Update, jump)
.run();
}
#[derive(Actionlike, PartialEq, Eq, Clone, Copy, Hash, Debug, Reflect)]
enum Action {
Run,
Jump,
}
#[derive(Actionlike, PartialEq, Eq, Clone, Copy, Hash, Debug, Reflect)]
enum Action2 {
A,
B,
}
#[derive(Component)]
struct Player;
fn spawn_player(mut commands: Commands) { …
```
> Fix `ToggleActions` from releasing other action's inputs

- examples/twin_stick_controller.rs
This is a fairly complete example that uses several of the concepts present in other examples.
The main new thing is the InputMode state, which detects MKB/gamepad input and switches an app state accordingly.
I also use an `ActionState` `Resource` here, as in #413 . I can change this to a component-based approach if preferred, but I think it gives quite a nice way to handle `ActionData` mutation without a driver.
I also wanted to add in some visuals here (a plane, a cube, etc.). But the crate doesn't include any of those dependencies from bevy. I didn't want to add these as dev dependencies, but happy to implement this too if you think it is worthwhile.
I'm still figuring things out, so happy to make any changes as requested.
> Adding an examples that implements a twin stick controller, with MKB/gamepad input

- src/input_mocking.rs
- src/input_streams.rs
- src/systems.rs
@alice-i-cecile I saw you were busy moving at the moment (congrats c:), but this should fix the issue with Bevy 0.12.1 that people mentioned in the discord.
Fixes #285
Cleanest fix I could come up with was to replace the `Events<T>` in `InputStreams` with `Vec<T>`, and then collecting the events into that with an `EventReader` in `update_action_state`.
> Fix mouse input events being read multiple times

- src/input_mocking.rs
- src/input_streams.rs
- src/lib.rs
This pull request splits the `MockInput` trait into three separate traits: `MockInput`, `QueryInput`, and `MockUIInteraction`.
Fixes #195
> Split MockInput trait

- src/input_mocking.rs
- src/input_streams.rs
The change in #418 to use a Vec instead of Events in MutableInputStreams broke input mocking for MouseMotion. I reverted the changes to MutableInputStreams so that it can send MouseMotion events. InputStreams remains unchanged. This brings the tests back to passing without undoing the effect of the original change. 
Fixes #419
> fixed mouse motion tests

- src/systems.rs
Fixes a compile error with the `egui` feature enabled when the `ui` or `block_ui_interactions` features are disabled.
> Fix `egui` feature compilation error 

- RELEASES.md
- src/input_map.rs
Sometimes it's useful to reset all mappings and re-populate it from scratch. Instead of creating a new `InputMap`, it's better to  reuse the allocated memory.
> Add `InputMap::clear`

- RELEASES.md
- examples/send_actions_over_network.rs
- src/action_state.rs
- src/systems.rs
- tests/action_diffs.rs
In this PR I added an `ActionDiff::AxisChanged` variant. This is meant to allow for transmitting changes to axis input types across the network. I've updated the relevant systems to handle creating events for this variant on the client and consuming them on the server. I've been using this solution in my own projects for a little bit and it seems to be working but I'm new to rust in addition to the bevy ecosystem so would really love some feedback as to if this seems like a reasonable solution. There are three potentially breaking changes. First I had to remove `Eq` and `Hash` from ActionDiff as f32 doesn't implement them.  Second I had to add a local resource to the `generate_action_diffs` system to keep track of if the axis actually changed. Lastly I had to add a requirement that the …
> Add ValueChange and AxisPairChange variants to ActionDiff

- src/input_map.rs
- src/input_streams.rs
Previously, I missed checking where the `InputStream::input_axis_pair()` function was used, got a bit worried that it might be widely used. However, upon investigation, it seems it’s just handling this way for `Chord`s—my bad! This made the solution more complex. So, I undid #432 (what I did earlier) and fixed up #430 again.
Fixing this problem should mainly involve checking if all buttons declared in the `Chord` are pressed. This simpler solution ([compared to the unchanged](https://github.com/Dzjudieng/leafwing-input-manager/compare/9d60abb..d3d0c00)) uses a for-loop that breaks out early. Perhaps it could potentially improve performance by avoiding redundant calculations to get the first dual axis data?
> A better solution to fix incorrect axis data in `Chord`

- examples/send_actions_over_network.rs
- src/action_state.rs
- src/systems.rs
- tests/action_diffs.rs
This PR reworks how networking via `ActionDiff` works:
- instead of using a "Stable `ID` Component" that uniquely identifies entities across client and server, we introduce the `ActionDiffEvent` type, which has:
- an owner: the Entity that generates the action, or None if we are using a global `ActionState`
- the action_diff itself
- we remove the `process_action_diffs` system in favor of a method `ActionState.apply_diff(action_diff)`, to leave more flexibility to users over how to process the action-diffs (perform entity-mapping, etc.)
I'm slightly confused about this: https://github.com/Leafwing-Studios/leafwing-input-manager/blob/main/src/systems.rs#L216: we detect if the button is Pressed/ValueChanged just based on the value?
What if we have a 'Value' type button that has a value of …
> Update action-diff to not include the stable component ID

- src/systems.rs
When the egui feature is enabled and the egui flag is used on a project using both bevy-egui and leafwing-input-manager, the program crashes with the following error:
```rust
thread 'Compute Task Pool (3)' panicked at C:\Users\Korisnik\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\system\system_param.rs:544:17:
Resource requested by leafwing_input_manager::systems::update_action_state<egui_test::Action> does not exist: bevy_egui::EguiUserTextures
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `leafwing_input_manager::systems::update_action_state<egui_test::Action>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
This fixes the crash by replacing the request for …
> Fix EguiUserTextures related crash when gui feature is nabled and bevy-egui is used

- src/action_state.rs
I ran into an issue (https://github.com/Leafwing-Studios/leafwing-input-manager/issues/443) when generating `ActionDiffs` for networking; it would be useful for me to be able to access whether a key was consumed or not.
> Add is_consumed getter

- RELEASES.md
- benches/action_state.rs
- examples/arpg_indirection.rs
- examples/clash_handling.rs
- examples/default_controls.rs
- examples/twin_stick_controller.rs
- macros/src/actionlike.rs
- src/action_state.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/lib.rs
- tests/actionlike_derive.rs
- tests/clashes.rs
- tests/mouse_motion.rs
- tests/mouse_wheel.rs
Fixes #412. Previously attempted in #415.
Turns out, doing one thing at once and using CI is helpful.
> Remove methods from `Actionlike` to support more complex Action types

- src/input_map.rs
The previous PR (#450) removed the accumulation for `ActionData::axis_pair` in `InputMap::which_pressed()`, resulting in a problem where multiple `DualAxisData` updates would only preserve the last one due to the loss of previously recorded `DualAxisData`.
```rust
InputMap::new([
(Action, VirtualDPad::arrow_keys()),
(Action, VirtualDPad::wasd()),
]);
```
While it functions correctly when pressing WASD, if only the arrow keys were pressed, `ActionState::axis_pair()` will return `None`.
Re-implement the accumulation of `ActionData::axis_pair` in `InputMap::which_pressed()`.
- Re-add the accumulation of `ActionData::axis_pair`
- Simplify the `ButtonState::JustPressed` check by moving it into the `input_pressed` checking block and remove the `pressed` flag
> Fix incorrect `ActionData::axis_pair` value when handling multiple `DualAxisData`

- Cargo.toml
- RELEASES.md
- macros/Cargo.toml
This is a breaking change release, but does *not* add support for Bevy 0.13. See #463 for that.
The idea here is to split this into two parts, to both better support users stuck on 0.12, and ease the migration process.
> Release 0.12

- src/action_state.rs
- src/axislike.rs
- src/clashing_inputs.rs
- src/display_impl.rs
- src/input_map.rs
- src/input_mocking.rs
- src/input_streams.rs
- src/orientation.rs
- src/systems.rs
- src/user_input.rs
- tests/action_diffs.rs
- tests/gamepad_axis.rs
Simplified PR #463 to refactor for clearer and more performant code.
- Refactored `DeadZoneShape::cross_deadzone_value()` and `DeadZoneShape::ellipse_deadzone_value()` to improve clarity of logic.
- Refactored `InputStreams::button_pressed()` and `InputStreams::input_value()` functions for both `MouseWheel` and `MouseMotion` events by using more efficient `f64` accumulation, reducing unnecessary `match`.
- Extracted `ActionState::action_data_mut_or_default()` function to remove duplication in the parts checking `press()`, `release()`, and `consume()`.
- Extracted `deadzone_axis_value()` to remove duplication in the parts applying deadzone to input values.
- Reused the existing `virtual_axis_button_clash()` for checking clashes of `VirtualAxis`.
- Extracted `send_keyboard_input()`, …
> Refactor for clearer and more performant code

- RELEASES.md
- src/action_state.rs
Fixes #471.
The actual issue lies in the incorrect updating of `ActionState` because it is now updated through a `HashMap` instead of a `Vec`, but the clashed `ActionData` has been removed (since #450).
```rust
// Handle clashes before #450
pub fn handle_clashes(
&self,
action_data: &mut [ActionData],
input_streams: &InputStreams,
clash_strategy: ClashStrategy,
) {
for clash in self.get_clashes(action_data, input_streams) {
// Remove the action in the pair that was overruled, if any
if let Some(culled_action) = resolve_clash(&clash, clash_strategy, input_streams) {
action_data[culled_action.index()] = ActionData::default();
}
}
}
// Update ActionData before #450
pub fn update(&mut self, action_data: Vec<ActionData>) {
assert_eq!(action_data.len(), A::n_variants());
for (i, action) in …
```
> Release the pressed `ActionData` when it isn't being updated

- RELEASES.md
- src/user_input.rs
Rename `Modifier::Win` to `Modifier::Super`, consistent with `KeyCode::SuperLeft` and `KeyCode::SuperRight` (since Bevy 0.11).
> [Breaking Changes] Rename `Modifier::Win` to `Modifier::Super`

- tools/ci/Cargo.toml
- tools/ci/src/main.rs
Make sure we thoroughly test all feature-related code and updates.
Cover all combinations of features our crate offers when running CI tests for `clippy`, ~~`doc-check`,~~ `doc-test`, `test`, and `compile-check`.
For instance, given the current existence of four features: `asset`, `ui`, `block_ui_interactions`, and `egui`, the new CI testing will include scenarios like:
- Testing with `--no-default-features`
- Testing with `--all-features`
- Testing with individual features enabled:
- `--features=asset`
- `--features=ui`
- `--features=block_ui_interactions`
- `--features=egui`
- Testing with various combinations of features enabled:
- `--features=asset,ui`
- `--features=asset,block_ui_interactions`
- `--features=asset,egui`
- `--features=ui,block_ui_interactions`
- `--features=ui,egui`
- …
> Add CI testing for all feature flag combinations and fix all reported errors

- Cargo.toml
- README.md
- RELEASES.md
- src/systems.rs
- tools/ci/src/main.rs
Currently, the `egui` feature prioritizes `egui` over actions during input processing for the `ActionState`.
However, the `ui` feature behaves differently unless both it and the `block_ui_interactions` feature are enabled (since #391).
To ensure consistency, make the `ui` feature behave like `egui` by removing the need for the `block_ui_interactions` feature.
Additionally, introduce a new `no_ui_priority` feature to disable the priority given by the `ui` feature.
By default, this library will prioritize `bevy::ui`, thus you could simply remove the `block_ui_interactions` feature from your `Cargo.toml`.
If you want to disable this priority, add the `no_ui_priority` feature to your configuration.
- Removed `block_ui_interactions` feature.
- Added `no_ui_priority` feature.
- Changed the …
> Align the behavior of the `ui` feature with `egui`

- src/action_state.rs
Export `action_data_mut_or_default`, which behaves the same way with `action_data_mut` in LWIM 0.11.
Just another unmentioned breaking changes of 0.12.
This should be particularly helpful for those working with setups similar to [this](https://discord.com/channels/691052431525675048/1034547742262951966/1209616393402581063).
> Export `action_data_mut_or_default`

- RELEASES.md
- macros/src/lib.rs
- src/action_state.rs
- src/axislike.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/input_streams.rs
- src/orientation.rs
- src/systems.rs
- src/user_input.rs
Continue with #466, and found other points that can be further cleaned up while rewriting `UserInput` and `InputStreams`.
- Added `with_threshold()` for const `SingleAxis` creation.
- Added `horizontal_gamepad_face_buttons()` and `vertical_gamepad_face_buttons()` for `VirtualAxis`, similar to  `VirtualDpad::gamepad_face_buttons()`.
- Changed various creations of `DualAxis`, `VirtualAxis`, `VirtualDpad` into const functions as they should be:
- `left_stick()`, `right_stick()` for `DualAxis`.
- `from_keys()`, `horizontal_arrow_keys()`, `vertical_arrow_keys()`, `ad()`, `ws()`, `horizontal_dpad()`, `vertical_dpad()` for `VirtualAxis`.
- `arrow_keys()`, `wasd()`, `dpad()`, `gamepad_face_buttons()`, `mouse_wheel()`, `mouse_motion()` for `VirtualDpad`.
- Removed the `DynActionMarker` derive. It …
> Const functions and cleanup

- README.md
- RELEASES.md
- examples/axis_inputs.rs
- examples/clash_handling.rs
- examples/default_controls.rs
- examples/minimal.rs
- examples/mouse_motion.rs
- examples/mouse_position.rs
- examples/mouse_wheel.rs
- examples/multiplayer.rs
- examples/press_duration.rs
- examples/register_gamepads.rs
- examples/send_actions_over_network.rs
- examples/single_player.rs
- examples/twin_stick_controller.rs
- examples/ui_driven_actions.rs
- examples/virtual_dpad.rs
- src/axislike.rs
- src/clashing_inputs.rs
- src/input_streams.rs
- src/lib.rs
- src/orientation.rs
- tests/integration.rs
Some thoughts after going through all the examples
Fixed a bug where `DualAxis` is being considered pressed even when its data is [0.0, 0.0] (since #438)
Found by [this chat](https://discord.com/channels/691052431525675048/1034547742262951966/1210379439544729751)
Added `InputManagerBundle::with_map(InputMap)`.
This allows you to create the bundle with the given `InputMap` and default `ActionState`
```rust
// before
InputManagerBundle {
input_map,
..Default::default()
};
// after
InputManagerBundle::with_map(input_map);
```
- simplified the usage of `InputManagerBundle` and `InputMap` via `InputManagerBundle::with_map`, `InputMap::new`, and `InputMap::insert` in examples and comments if it's possible
- removed incorrect description in the comments of twin_stick_controller.rs
- fixed all …
> Add `InputManagerBundle::with_map` and fix a mishandling of DualAxis

- Cargo.toml
- RELEASES.md
- examples/single_player.rs
- src/axislike.rs
- src/orientation.rs
Remove `Direction` and replace all usages with `Direction2d` from Bevy, preserving all conversions and replacing usages.
Fixes #487
> Remove Direction in favour of Direction2d from Bevy

- examples/multiplayer.rs
When reading the multiplayer example it wasn't entirely clear how to query for
each player state directly, as a lot of the examples the the ActionState as a
resource, thus making it a singleton. Adding this usage pattern in the example
makes it just a bit clearer.
I added a system that uses the actions that were provided in the setup system in
the multiplayer example.
> docs: add multiplayer action usage example

- RELEASES.md
- examples/default_controls.rs
- src/input_map.rs
- src/input_streams.rs
- tests/multiple_gamepads.rs
Fixes #500 (again), as an alternative to the solution provided in #501.
This also adds a new test group (`tests/multiple_gamepads.rs`) and (hopefully) clarifies the documentation for `InputMap.set_gamepad()`.
> Fixed gamepad filtering (alternate branch)

- README.md
- RELEASES.md
- benches/input_map.rs
- examples/action_state_resource.rs
- examples/arpg_indirection.rs
- examples/axis_inputs.rs
- examples/clash_handling.rs
- examples/input_processing.rs
- examples/mouse_wheel.rs
- examples/multiplayer.rs
- examples/register_gamepads.rs
- examples/send_actions_over_network.rs
- examples/virtual_dpad.rs
- src/action_state.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/systems.rs
- added new fluent builders for creating a new `InputMap<A>` with short configurations:
- `fn with(mut self, action: A, input: impl Into<Item = UserInput>)`.
- `fn with_one_to_many(mut self, action: A, inputs: impl IntoIterator<Item = UserInput>)`.
- `fn with_multiple(mut self, bindings: impl IntoIterator<Item = (A, UserInput)>) -> Self`.
- `fn with_gamepad(mut self, gamepad: Gamepad) -> Self`.
- added new iterators over `InputMap<A>`:
- `bindings(&self) -> impl Iterator<Item = (&A, &UserInput)>` for iterating over all registered action-input bindings.
- `actions(&self) -> impl Iterator<Item = &A>` for iterating over all registered actions.
- removed `InputMap::build` method in favor of new fluent builder pattern.
- renamed `InputMap::which_pressed` method to `process_actions` to better …
> Add new fluent builders and iterators for `InputMap`

- README.md
- RELEASE-CHECKLIST.md
- RELEASES.md
- benches/input_map.rs
- examples/send_actions_over_network.rs
- src/action_state.rs
- src/axislike.rs
- src/buttonlike.rs
- src/clashing_inputs.rs
- src/input_mocking.rs
- src/input_processing/dual_axis/circle.rs
- src/input_processing/dual_axis/mod.rs
- src/input_streams.rs
- src/user_input.rs
- tests/clashes.rs
- tests/gamepad_axis.rs
- tests/integration.rs
- tests/mouse_motion.rs
- tests/mouse_wheel.rs
- should be merged once #514 was merged.
- added new methods for sending value changed events to each axis within the input:
- `fn send_axis_values(&self, input: UserInput, values: impl IntoIterator<Item = f32>)`.
- `fn send_axis_values_as_gamepad(&self, input: UserInput, values: impl IntoIterator<Item = f32>, gamepad: Option<Gamepad>)`.
- renamed `MockInput::send_input` method to `MockInput::press_input` to better reflect its current functionality for clarity.
- removed the hacky `value` field and `from_value` method from `SingleAxis` and `DualAxis`, in favor of new input mocking API.
If you were using the `send_input` method for buttons and keys to send simulated pressed events, simply update the method name to `press_input`.
If you were using the `value` field or the `from_value` …
> Remove the hacky `value` field and `from_value` method of axis-like inputs in favor of a new input mocking API

- src/input_mocking.rs
- removed mouse released event mocking (added in #515) as LWIM already checks the state from events each frame, making this redundant
- minor improved the docs for clarity
> Remove mock released events for mouse input and minor improve the docs

- examples/axis_inputs.rs
- src/input_processing/dual_axis/mod.rs
- src/input_processing/dual_axis/range.rs
- src/input_processing/mod.rs
- src/input_processing/single_axis/mod.rs
- src/input_processing/single_axis/range.rs
- tests/gamepad_axis.rs
- Renamed all `magnitude_` methods of range processors and WithProcessorExt traits to `_symmetric` for clarity
- Added more methods that append range processor for both negative and positive sides, as well as symmetrical ranges
> Enhance consistency of methods for processors and `WithProcessorExt` traits

- RELEASES.md
- examples/input_processing.rs
- src/axislike.rs
- src/input_processing/dual_axis/mod.rs
- src/input_processing/mod.rs
- src/input_processing/single_axis/mod.rs
- tests/gamepad_axis.rs
- renamed `WithProcessorExt` to `WithProcessingPipelineExt`
- added `Processor::pipeline` methods
Additionally, removed a missing duplicate in `VirtualAxis` and rearranged the RELEASES.md
> Rename `WithProcessorExt` to `WithProcessingPipelineExt` and add methods for processors

- RELEASES.md
- benches/action_state.rs
- src/action_state.rs
- src/lib.rs
- src/plugin.rs
- src/systems.rs
- tests/integration.rs
Fixes https://github.com/Leafwing-Studios/leafwing-input-manager/issues/446, https://github.com/Leafwing-Studios/leafwing-input-manager/issues/416.
Don't disable the systems that update action state. Instead, include a `disabled` flag per action within `ActionState<A>`. While `disabled` is `true`, an action will always read as released, regardless of its actual state.
Pros:
- Replaces `ToggleActions<A>`, making the API surface area smaller.
- Supports granular enabling / disabling between:
- The individual actions of an `ActionState<A>`
- Different entities with the same `ActionState<A>` component type
- Resource vs component instances of `ActionState<A>`
- Keeps the action update logic simple and consistent by only affecting how the state is read, not how it's written.
- Similar to the …
> Replace `ToggleActions<A>` with per-action disable flags

- src/lib.rs
A trivial/harmless problem: `Hash` occurs twice in the trait bounds.
> Remove duplicate Hash bound for Actionlike

- RELEASES.md
Haven't been following this repo closely, so please feel free to close if this isn't useful right now.
I recently witnessed some mild confusion on Discord related to the main branch changelog's contents.
- Show correct future version number for unreleased changes
- Add 0.14's changelog entry
> Update RELEASES for 0.14

- RELEASES.md
- benches/action_state.rs
- src/action_state/action_data.rs
- src/action_state/mod.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/systems.rs
Fixes #553.
Prompted by @cBournhonesque, this PR refactors the internals of `ActionState`: restoring the `ActionData` type, and moving shared data into that struct.
> Share metadata across action types and only store a single Hashmap in ActionState

- RELEASES.md
- src/action_state/mod.rs
- src/systems.rs
- tests/integration.rs
Fixes #563.
I've added `ActionState` level disabling in this PR, while documenting how to disable action updates via run conditions.
The other change that I've made is releasing / resetting all actions when they get disabled: actions started before a cutscene begins should not surprisingly resume upon its conclusion.
> Add ActionState-level disabling

- RELEASES.md
This ensures that each header can be linked to, but more importantly, silences markdownlint's 52 warnings.
> Add version numbers to RELEASES.md section headers

- RELEASES.md
- src/action_state/mod.rs
- src/input_map.rs
blenvy requires the ReflectComponent data when instantiating blueprints.
> Reflect InputMap and ActionState

- src/action_state/action_data.rs
The fix is simply to use bevy_utils::Instant instead of std::time::Instant in action_data.
Fixes #589.
> Fixes #589: compilation for target wasm32-unknown-unknown

- RELEASES.md
- src/action_diff.rs
Implementing `MapEntities` for `ActionDiffEvent`s allows networking crates like replicon to automatically translate the ID of the "owner entity" for action diffs from the client's set of entity IDs to the server's (or vice versa).
------------------
I'm new to contributing to LWIM, should I open an issue first? Let me know if anything else is needed :)
> Implement MapEntities for ActionDiffEvent

- RELEASES.md
- examples/axis_inputs.rs
- examples/default_controls.rs
- examples/input_processing.rs
- examples/mouse_motion.rs
- examples/mouse_wheel.rs
- examples/twin_stick_controller.rs
- examples/virtual_dpad.rs
- macros/src/actionlike.rs
- macros/src/lib.rs
- macros/src/typetag.rs
- src/action_diff.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/lib.rs
- tests/action_diffs.rs
- tests/gamepad_axis.rs
- tests/mouse_motion.rs
- tests/mouse_wheel.rs
- Fixes #587
Added an `#[actionlike]` attribute to enhance ergonomics.
You can apply this attribute to the entire enum to set a default behavior for all action variants, or to individual variants to override the default behavior.
By default, all actions are treated as button-like, as they were previously.
```rust
#[derive(Actionlike, Debug, PartialEq, Eq, Clone, Copy, Hash, Reflect)]
#[actionlike(Axis)] // All variants in this enum are controlled by axes
enum CameraAction {
Zoom,  // This action is controlled by axes
#[actionlike(DualAxis)]
Move,  // This action is controlled by dual axes since we have overrode the default option
#[actionlike(Button)]
TakePhoto, // This action is controlled by buttons since we have override the default option
}
```
> Add `#[actionlike]` for actions to set their `InputControlKind`s

- RELEASES.md
- src/action_diff.rs
- src/action_state/action_data.rs
- src/action_state/mod.rs
- src/clashing_inputs.rs
- src/input_map.rs
- src/lib.rs
- src/plugin.rs
- src/user_input/chord.rs
- src/user_input/keyboard.rs
- src/user_input/mod.rs
- src/user_input/trait_reflection.rs
- src/user_input/trait_serde.rs
- src/user_input/updating.rs
- tests/action_diffs.rs
- added `TripleAxislike` trait for inputs that track all X, Y, and Z axes.
- added `KeyboardVirtualDPad3D` that consists of six `KeyCode`s to represent a triple-axis-like input.
- added `TripleAxislikeChord` that groups a `Buttonlike` and a `TripleAxislike` together.
- added related variants such as:
- `InputControlType::TripleAxis`
- `ActionDiff::TripleAxisChanged`
> Add `TripleAxislike`

- RELEASES.md
- examples/action_state_resource.rs
- examples/axis_inputs.rs
- examples/default_controls.rs
- examples/twin_stick_controller.rs
- examples/virtual_dpad.rs
- src/action_state/mod.rs
- src/input_map.rs
- src/user_input/mod.rs
Fixes #591. The press_duration example looks more involved, so that's been spun out into #612.
> Fix buggy examples

- RELEASES.md
- examples/twin_stick_controller.rs
- src/input_map.rs
`InputMap::merge` is now compatible with all input kinds, previously limited to buttons
> Fix `InputMap::merge`

- RELEASES.md
- src/input_processing/dual_axis/circle.rs
- src/input_processing/dual_axis/mod.rs
- src/input_processing/dual_axis/range.rs
- src/input_processing/single_axis/mod.rs
- src/input_processing/single_axis/range.rs
- added missing docs about panicking.
- allowed creating `DualAxisBounds`, `DualAxisExclusion`, and `DualAxisDeadZone` from their struct definitions directly.
- added `at_least` and `at_most` methods for those implementing `WithAxisProcessorExt` trait.
- added `at_least`, `at_least_only_x`, `at_least_only_y`, `at_most`, `at_most_only_x`, and `at_most_only_y` methods for those implementing `WithDualAxisProcessorExt` trait.
- added `only_positive` and `only_negative` builders for `AxisDeadZone` and `AxisExclusion`.
- added corresponding extension methods for those implementing `WithAxisProcessorExt` trait.
- added `only_positive`, `only_positive_x`, `only_positive_y`, `only_negative`, `only_negative_x`, and `only_negative_y` builders for `DualAxisDeadZone` and `DualAxisExclusion`.
- added …
> Add new builders for input processors and extensions for those implementing `WithInputProcessorExt` traits

- src/action_state/mod.rs
- src/plugin.rs
It seems that there's no API in Bevy that allows to configure running conditions of individual systems, which makes it impossible to disable action updates of type `A` as suggested in the documentation. This PR adds the `TickActionStateSystem` set to work this around.
> Add `TickActionStateSystem` set to allow configuring `tick_action_state` individually

- .cargo/config.toml
- .github/workflows/ci.yml
- Cargo.toml
- tools/ci/src/main.rs
> Add wasm32 build to ci (#636)

- RELEASES.md
- src/axislike.rs
- src/user_input/gamepad.rs
- src/user_input/mouse.rs
- Added a `threshold` field to `GamepadControlDirection`
- Renamed the `side` field of `GamepadControlDirection` to `direction` for clarity
- Changed the struct definitions of `MouseMoveDirection` and `MouseScrollDirection` from tuple structs to regular structs with `threshold` and `direction` fields
> Add `threshold` value for `GamepadControlDirection`, `MouseMoveDirection`, and `MouseScrollDirection`

- RELEASES.md
- src/action_diff.rs
- src/systems.rs
- tests/action_diffs.rs
> Add ability to filter entities for which action diffs should be generated

- src/user_input/gamepad.rs
- src/user_input/keyboard.rs
- src/user_input/mouse.rs
- src/user_input/updating.rs
This PR builds upon @pcwalton's excellent work in #644 by extracting the better `SourceData` type of `UpdatableInput` into a separate small PR for better organisation
> Switch source data of `UpdatableInput` from `Res` to `SystemParam`

- RELEASES.md
- src/plugin.rs
- src/user_input/trait_serde.rs
In our project, we want to store and load control to `.ron` file. 
After update to `0.15` there was error `tokens failed to deserialize: no deserialize function was registered for id '"MouseButton"'`
I checked the latest fixes, and it looks like there was just missing `register_buttonlike_input` for `MouseButton`
> Add deserializer function for MouseButton

- src/user_input/gamepad.rs
- src/user_input/mouse.rs
- src/user_input/virtual_axial.rs
Fixes #656
Makes it easier to tune controls using inspectors and also to construct VirtualDPads using dynamic values.
> Make processors, Virtual pads, and GamepadStick fields public

- Cargo.toml
- macros/src/actionlike.rs
- src/input_processing/dual_axis/custom.rs
- src/input_processing/single_axis/custom.rs
- src/user_input/trait_serde.rs
This fixes nightly rustc yelling about:
error: creating a shared reference to mutable static is discouraged
--> src/user_input/trait_serde.rs:69:37
|
69 |         let mut registry = unsafe { AXISLIKE_REGISTRY.write().unwrap() };
|                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ shared reference to mutable static
|
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
= note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
And drops a dependency.
Ref #662 which had build failures.
> registries: no need for `static mut` or unsafe + use std's LazyLock

- macros/src/actionlike.rs
This fixes compile errors in non-cargo build systems, which rely on the rustc crate hash being the same between two compiles (i.e. build with/without codegen).
HashMap order is nondeterministic due to SipHasher initialization, so macro-generated code would change between compiles (in this case, the order of the generated match statement branches).
Can confirm buck2 can now build and link leafwing-input-manager.
> Make the macros deterministic, using BTreeMap instead of HashMap

- tests/buttonlike.rs
Fixes the ignored tests introduced in #664 .
The reason these tests were failing was because the [`find_gamepad`](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/d40715f2cf13aa3d3bcaa8fc5c33ed65c7abb8fd/src/user_input/gamepad.rs#L37) function was changed to rely on the existence of a `Gamepad` component to find a gamepad entity if no entity reference was directly provided, however this was not being added.
> Fix ignored tests from update to bevy 0.15

- Cargo.toml
- src/plugin.rs
This makes sure that action state updates from e.g pointer click observers happens after the state reset of LWIM.
> Explicitly order LWIM and bevy_picking system sets

- Cargo.toml
Pruning some duplicate versions from cargo tree in my project and found derive_more to be unused in lwim
> Remove unused derive_more dependency

- Cargo.toml
- RELEASES.md
- src/plugin.rs
I've disabled default-features (which might save some compilation time for someone), and removed `after(bevy_egui::EguiSet::ProcessInput)` from the system ordering.
Egui writes it to memory whether it wants mouse/keyboard input only during its `end_pass`, which happens in the `PostUpdate` schedule, and since we want to run filtering during `PreUpdate`, the system ordering is redundant (`wants_pointer_input` and others always have a 1-frame delay anyway).
> Update bevy_egui to 0.32

- examples/arpg_indirection.rs
- examples/register_gamepads.rs
- src/action_diff.rs
- src/action_state/action_data.rs
- src/action_state/mod.rs
- src/input_map.rs
- src/input_processing/mod.rs
- src/systems.rs
- src/timing.rs
- src/user_input/chord.rs
- src/user_input/gamepad.rs
- src/user_input/keyboard.rs
- src/user_input/mod.rs
- src/user_input/mouse.rs
- src/user_input/updating.rs
- src/user_input/virtual_axial.rs
- tests/clashes.rs
Based on #686 
Fixes the docs indentation error from clippy, and moves the `#[must_use]` attributes on the `{Button,Axis,DualAxis,TripleAxis}Like` implementations to the trait definition itself to fix a warning on nightly versions.
> Fix warnings

- Cargo.toml
- RELEASES.md
- src/plugin.rs
- src/systems.rs
- src/user_input/updating.rs
- tools/ci/src/main.rs
Based on #686.
Since `bevy_egui` now implements absorbing inputs (https://github.com/vladbat00/bevy_egui/pull/369, https://github.com/vladbat00/bevy_egui/pull/373), we shouldn't have both libraries possibly fighting over inputs. This PR removes the Egui feature completely.
Also, this PR adds an `EnabledInput` resource to make it possible to disable certain inputs without absorbing `ButtonInput<T>` for every possible system existing in an app, providing a more granular approach.
I haven't removed the `ui` feature as I thought some users might still benefit from it if they don't use `bevy_egui`.
> Replace Egui with disableable inputs

- Cargo.toml
- RELEASES.md
- src/input_map.rs
PR introduces additional methods that allow using boxed versions of the traits directly.
Previous methods have been adapted to use the boxed versions underlying, and the boxed methods run all the (previous) logic to them.
Relevant issue: #620
> Introduce boxed methods for insertion.

- src/action_state/mod.rs
Fixes #612 and `previous_duration` not working
`flip()` was called two times, both by update and fixed update, erasing the `previous_duration` value in `ButtonData`'s `Timing`. I switched `flip()` check to only use update data to fix it
> Fixes #612 and `previous_duration`
