Cargo.toml
src/action_state.rs
src/clashing_inputs.rs
src/input_map.rs
src/user_input.rs

Serialization and deserialization

---

Cargo.toml
src/input_mocking.rs
src/plugin.rs
src/systems.rs
tests/integration.rs

I moved all `bevy_ui` related functionality under a feature, closes #80.

Move bevy_ui dependency under a feature

---

RELEASES.md

Forgot to add a change to `RELEASES.md` from #84.

Add missing change to RELEASES.md

---

src/input_map.rs

Just to make it look a little nicer.

IntoIter alias

---

src/clashing_inputs.rs
src/input_map.rs

In this PR I removed caching to simplify the code and remove cache from the serialization.

Remove clashing input caching

---

Cargo.toml
examples/arpg_indirection.rs
examples/send_actions_over_network.rs
src/action_state.rs
src/axislike_user_input.rs
src/buttonlike_user_input.rs
src/clashing_inputs.rs
src/errors.rs
src/input_map.rs
src/input_mocking.rs
src/lib.rs
src/orientation.rs
src/plugin.rs
src/systems.rs
tests/clashes.rs
tests/integration.rs

This results in better compile times, and makes it easier to add Cargo features.

Depend on bevy subcrates

---

RELEASES.md
src/lib.rs
src/plugin.rs
src/systems.rs
tests/integration.rs

Replace run_in_state with DisableInput resource

---

src/systems.rs

Follow-up from @shatur's comments in #109.

Naming nits

---

RELEASES.md
src/action_state.rs
src/buttonlike.rs
src/clashing_inputs.rs

- FIxes #108
- Incidentally makes the VirtualButtonState constants clearer: they reflect a JustX state
@shatur, can I get your review on this? I want to make sure that this will do what you're hoping for.

ActionState::reset API

---

Cargo.toml
examples/consuming_actions.rs
examples/send_actions_over_network.rs
src/input_mocking.rs
tests/integration.rs

This is blocked on the new release of bevy_egui: https://github.com/mvlabat/bevy_egui/issues/88
If it's too long, we may just want to cut the menu example for now.

Update to Bevy 0.7

---

RELEASES.md
src/plugin.rs
src/systems.rs

Properly document ToggleActions

---

RELEASES.md
src/plugin.rs

Improve plugin-level docs

---

RELEASES.md
src/action_state.rs

Expand ActionStateDriver docs

---

README.md

Demonstrate minimal usage of crate in README

---

Cargo.toml
RELEASES.md
examples/arpg_indirection.rs
examples/press_duration.rs
src/action_state.rs
src/systems.rs
tests/integration.rs

Fix broken duration pressed functionality

---

Cargo.toml
RELEASES.md

sync up macros dependency with macros crate name

---

Cargo.toml
RELEASES.md
macros/Cargo.toml

A simple cleanup PR, which should make merge conflicts less bad.

Merge changes from main into dev branch

---

Cargo.toml
examples/binding_menu.rs
examples/multiplayer.rs
examples/press_duration.rs
examples/ui_driven_actions.rs
src/axislike.rs
src/input_map.rs
src/input_mocking.rs
src/orientation.rs
src/systems.rs
src/user_input.rs

Built off of the lovely work in #133 by @BlackPhlox.
The `egui` example seems impossible to make pass just yet; we'll have to remember to fix that just before release.

Update to Bevy 0.8-dev

---

Cargo.toml
src/input_map.rs

Git is a reliable and intuitive piece of software.

Fix broken dependencies induced by merge conflict resolution

---

RELEASES.md
examples/mouse_motion.rs
src/axislike.rs
src/buttonlike.rs
src/display_impl.rs
src/input_map.rs
src/input_mocking.rs
src/input_streams.rs
src/orientation.rs
src/systems.rs
src/user_input.rs

Fixes #184. 
Shockingly easy; this was nearly a copy-paste of the mouse motion code. There's probably room there for deduplication, but I want to wait until #178 is fixed before attempting it.

Add mouse motion support

---

Cargo.toml
examples/binding_menu.rs

Also bump bevy_egui dependency!
Fixes #181.

Bump to Bevy 0.8

---

RELEASES.md
examples/send_actions_over_network.rs
src/action_state.rs
src/clashing_inputs.rs
src/input_map.rs
src/input_mocking.rs
src/input_streams.rs
src/lib.rs
src/systems.rs
tests/clashes.rs
tests/integration.rs
tests/mouse_wheel.rs

This dramatically simplifies the internals and testing, and likely has a non-zero performance impact.
Incremental progress towards #183, done in pursuit of solving the bugs in #178.

Make input stream fields non-optional

---

RELEASE-CHECKLIST.md
RELEASES.md
src/input_map.rs
src/input_mocking.rs
src/input_streams.rs

Clean up input mocking code

---

RELEASE-CHECKLIST.md
src/axislike.rs
src/input_mocking.rs
tests/gamepad_axis.rs
tests/mouse_motion.rs
tests/mouse_wheel.rs

Progress towards #178. Gamepad axislike inputs appear to still be broken.

Fix axislike input mocking (kind of)

---

Cargo.toml

Fix crate name in Cargo.toml

---

Cargo.toml
RELEASES.md

Bump version number to 0.5.1

---

.github/workflows/ci.yml

Closes #196.
I opted for `ubuntu-latest`, because it was already used in some other CI jobs.
Apparently, VS Code also auto-formatted the YAML file, I can revert this if you want.

Change CI workflow to run on ubuntu-latest

---

RELEASES.md
examples/arpg_indirection.rs
examples/axis_inputs.rs
examples/minimal.rs
examples/mouse_motion.rs
examples/mouse_wheel.rs
examples/press_duration.rs
examples/send_actions_over_network.rs
examples/single_player.rs
examples/virtual_dpad.rs
src/action_state.rs
src/cooldown.rs
src/lib.rs
src/plugin.rs
src/systems.rs
tests/cooldowns.rs

This avoids entangling concerns and is more discoverable.

Store Cooldowns in a component

---

RELEASES.md
src/axislike.rs

Rebase of #230 by @Pulau-Komodo <3

Add `with_deadzone` setters for axes

---

src/cooldown.rs
tests/cooldowns.rs

Add global cooldowns

---

RELEASES.md
examples/binding_menu.rs
examples/consuming_actions.rs
examples/minimal.rs
src/charges.rs
src/cooldown.rs
src/lib.rs
src/systems.rs
tests/actionlike_derive.rs
tests/cooldowns.rs

Fixes #256.
These components are much easier to reason about and more flexible if they are seperate.

Split cooldowns and charges

---

RELEASES.md
src/axislike.rs
src/clashing_inputs.rs
src/display_impl.rs
src/input_streams.rs
src/user_input.rs

Similar to `VirtualDPad`, but for one axis only.
Closes: #216

Add VirtualAxis

---

src/systems.rs

This PR makes the `egui` feature handle more gracefully: having no effect rather than panicking if the corresponding egui context resource is not found.
I ran into this at work today, as we're using LWIM in headless mode (but not egui). Rather than hack around it, I figured I should fix it for everyone :)

Only deal with egui if the resource exists

---

Cargo.toml
RELEASES.md

Just egui feature fixes in this one :)

Prepare for 0.7.1 release

---

Cargo.toml
RELEASES.md

A small point release to get some user-contributed fixes and features out there :)

Bump version number to prepare for release

---

examples/axis_inputs.rs
examples/binding_menu.rs
src/display_impl.rs

Fixes the `uninlined_format_args` lint to make CI pass again.

Fix `uninlined_format_args` lint

---

examples/single_player.rs

Left should be west and right should be east

Fix incorrect directions

---

src/input_map.rs

added two helper methods to make it simpler to add many-to-one mappings

add many to one and one to many insert methods

---

Cargo.toml
RELEASES.md
macros/Cargo.toml

- Add release notes for new scan code feature
- Bump crate version to 0.9

Prepare release 0.9

---

RELEASES.md
src/common_conditions.rs
src/lib.rs

Mirrors https://github.com/bevyengine/bevy/blob/main/crates/bevy_input/src/common_conditions.rs

Add common conditions

---

Cargo.toml
benches/action_state.rs
benches/input_map.rs
src/clashing_inputs.rs

Fixes #121.
```
Running benches/action_state.rs (target/release/deps/action_state-0497b931c1ae8758)
action_state_default    time:   [51.787 ns 51.848 ns 51.908 ns]
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) low mild
3 (3.00%) high mild
1 (1.00%) high severe
pressed                 time:   [95.819 ps 96.571 ps 97.350 ps]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
just_pressed            time:   [99.635 ps 100.27 ps 100.84 ps]
Found 7 outliers among 100 measurements (7.00%)
5 (5.00%) low mild
2 (2.00%) high mild
released                time:   [103.09 ps 103.56 ps 104.00 ps]
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low severe
6 (6.00%) low mild
just_released           time:   [103.43 ps 103.81 ps 104.17 ps]
Found 8 outliers among 100 …
```

Add basic benchmarks

---

.github/workflows/ci.yml
examples/virtual_dpad.rs
macros/src/actionlike.rs
macros/src/lib.rs
src/action_state.rs
src/axislike.rs
src/buttonlike.rs
src/errors.rs
src/input_map.rs
src/input_mocking.rs
src/lib.rs
src/orientation.rs
src/plugin.rs
src/press_scheduler.rs
src/systems.rs
src/user_input.rs
tools/ci/Cargo.toml
tools/ci/src/main.rs

Fixes #325.
Thanks and credit to @TimJentzsch for figuring this out intially in the Emergence repo.

Use a faster, cached CI setup

---

RELEASES.md
examples/mouse_motion.rs
examples/mouse_wheel.rs
examples/multiplayer.rs
examples/send_actions_over_network.rs
src/clashing_inputs.rs
src/display_impl.rs
src/input_map.rs
src/input_mocking.rs
src/orientation.rs
src/plugin.rs
src/scan_codes/mac_os.rs
src/systems.rs
src/user_input.rs

Fix a few typos, no functional changes.

Fix a few typos

---

RELEASES.md
src/axislike.rs

I was a little surprised these two helpers were not here, so I added them. Hopefully not a controversial change.

add horizontal_dpad and vertical_dpad to VirtualAxis

---

RELEASES.md
src/orientation.rs

Increase rotation precision to a millionth of a degree

---

Cargo.toml
RELEASES.md

Prepare for version 0.9.3

---

CONTRIBUTING.md

Contributors should update RELEASES.md

---

RELEASES.md
src/plugin.rs

Fix system order ambiguity between bevy_ui and update_action_state systems

---

RELEASES.md
examples/default_controls.rs

Fixes #248 
This is my first time creating an example, so I'd be happy to hear any feedback on the comments. Is this what you had in mind for the example?

Default controls example

---

src/plugin.rs

Closes #383 
I tested minimal, ui_driven_actions, and bindings_menu to test different features. They all worked as expected.

Fix compile error when default features are off

---

RELEASES.md
examples/register_gamepads.rs
src/plugin.rs

Fixes #18
Teaches how to use LWIM for joining with gamepads in a local multiplayer fashion.

Add gamepad registration example

---

Cargo.toml
RELEASES.md
examples/send_actions_over_network.rs
macros/Cargo.toml
src/input_map.rs
src/input_streams.rs
src/plugin.rs
src/systems.rs
tests/gamepad_axis.rs

The first two commits was fixing the merge conflicts.

Switch `A::variants()` to `self.iter()`

---

RELEASES.md
src/input_map.rs

Fix incorrect axis data in `Chord` when not all buttons are pressed

---

src/systems.rs

Update action-diff-system docstring

---

src/clashing_inputs.rs
src/plugin.rs

For some reason I could not get the `clippy::get_first` error to show up even when using the same commands as the Github Actions.

Fix lint and doc errors

---

RELEASES.md
src/axislike.rs
src/input_streams.rs
src/lib.rs
tests/gamepad_axis.rs
tests/mouse_motion.rs
tests/mouse_wheel.rs

Closes #398
The issue above describes the changes made and why really well.
To-Do:

Accessible Deadzones

---

Cargo.toml
README.md
RELEASES.md

Fixes #461
Additionally, fix a minor issue in the example in README.md, and add an item I forgot to mention (#459) in RELEASES.md.

Document crate feature flags in README and Cargo.toml

---

Cargo.toml
README.md
RELEASES.md
src/input_map.rs
src/input_mocking.rs

Simplified PR #463 to address compilation issues and improve documentation.

Add supported Bevy versions and feature gates

---

src/action_state.rs

Prefer `HashMap::values_mut()`

---

benches/input_map.rs
examples/arpg_indirection.rs
examples/axis_inputs.rs
examples/consuming_actions.rs
examples/mouse_wheel.rs
examples/multiplayer.rs
examples/register_gamepads.rs
examples/send_actions_over_network.rs
examples/twin_stick_controller.rs
src/action_diff.rs
src/action_driver.rs
src/action_state.rs
src/axislike.rs
src/buttonlike.rs
src/clashing_inputs.rs
src/input_map.rs
src/input_mocking.rs
src/input_streams.rs
src/orientation.rs
src/plugin.rs
src/systems.rs
src/timing.rs
src/user_input.rs
tests/gamepad_axis.rs
tests/integration.rs
tests/mouse_motion.rs
tests/mouse_wheel.rs

Apply suggestions from grammar check in the comments

Apply suggestions from grammar check

---

examples/input_processing.rs
src/input_processing/dual_axis/mod.rs
src/input_processing/mod.rs
src/input_processing/single_axis/mod.rs

Prefer `FromIter<*AxisProcessor>` over `From<Vec<*AxisProcessor>>`

---

Cargo.toml
README.md
RELEASES.md
benches/action_state.rs
src/action_state.rs
src/lib.rs
src/plugin.rs
tests/integration.rs
tools/ci/src/main.rs

Fixes https://github.com/Leafwing-Studios/leafwing-input-manager/issues/525

Add timing data behind a feature

---

src/orientation.rs

Fix #528 
Fix a small issue with the docs for micro_degrees

Fix docs for Rotation micro_degrees field

---

Cargo.toml
RELEASES.md
examples/input_processing.rs
src/axislike.rs
src/clashing_inputs.rs
src/input_processing/dual_axis/mod.rs
src/input_processing/mod.rs
src/input_processing/single_axis/mod.rs
tests/gamepad_axis.rs

- #511 added unnecessary abstraction

Switch axis processing pipeline to `Vec`

---

src/input_processing/dual_axis/custom.rs
src/input_processing/single_axis/custom.rs

Fix TODO try_apply methods

---

README.md

Update README for 0.14

---

examples/virtual_dpad.rs

Fix virtual_dpad example

---

src/action_diff.rs
src/action_state/action_data.rs
src/action_state/mod.rs
src/input_map.rs
src/lib.rs
src/user_input/chord.rs
src/user_input/gamepad.rs
src/user_input/keyboard.rs
src/user_input/mouse.rs
src/user_input/trait_reflection.rs
src/user_input/updating.rs
tests/action_diffs.rs

- Clean up some outdated docs
- Remove some redudent docs
- Fix typos
- Inline some internal functions

Update outdated docs and simplify internal code

---

src/clashing_inputs.rs

Fix mistake in docs about clashing inputs

---

src/plugin.rs
src/systems.rs

Fixes https://github.com/Leafwing-Studios/leafwing-input-manager/issues/604.

Fix egui input filtering

---

Cargo.toml
examples/arpg_indirection.rs
examples/axis_inputs.rs
examples/clash_handling.rs
examples/default_controls.rs
examples/input_processing.rs
examples/minimal.rs
examples/mouse_motion.rs
examples/mouse_wheel.rs
examples/press_duration.rs
examples/register_gamepads.rs
examples/send_actions_over_network.rs
examples/single_player.rs
examples/twin_stick_controller.rs
examples/virtual_dpad.rs
src/action_diff.rs
src/action_state/action_data.rs
src/action_state/mod.rs
src/input_map.rs
src/plugin.rs
src/systems.rs
src/timing.rs
src/user_input/keyboard.rs
src/user_input/updating.rs
tests/action_diffs.rs
tests/clashes.rs
tests/integration.rs

Straight forward upgrade, I added dependencies for bevy_log, and std for bevy::math and transform, not sure thats ideal.

update to bevy 0.16

---

README.md
RELEASES.md
examples/axis_inputs.rs
examples/clash_handling.rs
examples/default_controls.rs
examples/input_processing.rs
examples/minimal.rs
examples/mouse_motion.rs
examples/mouse_wheel.rs
examples/multiplayer.rs
examples/register_gamepads.rs
examples/send_actions_over_network.rs
examples/single_player.rs
examples/virtual_dpad.rs
src/input_map.rs
src/lib.rs
tests/integration.rs

Builds on @atornity's work in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/676
- Merge main and resolve conflicts
- Document expected deprecation warnings

use required components for InputMap (requires ActionState) 2

---

README.md

Added leafwing-input-manager 0.17 -> bevy 0.16

Update list of supported Bevy versions in Readme
